version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: realestate_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - ./data:/app/data
      - ./ingest.py:/app/ingest.py
    depends_on:
      - postgres
    command: > 
      bash -c "./download_data.sh"

volumes:
  db-data:
